name: Component-based Checks

on:
  pull_request:
    branches:
    - main

jobs:
  go_service_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.5'
        
      - name: Run Go tests
        run: |
          cd technician-service
          go test ./...
  
  go_service_checks2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.5'
      - name: Run Go tests
        run: |
          cd available-technician-service
          go test ./...     
  
  java_service_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
        
      - name: Run Java checks
        run: |
          cd user-service
          mvn test